### ISSUE TITLE
Local Option Not Implemented Correctly

### ISSUE THREAD

**Issue by ryanfitzer** [siygle/grunt-autoshot#1]
The [`url` option](https://github.com/Ferrari/grunt-autoshot/blob/master/tasks/autoshot.js#L105) does not specify a page for phantomjs to open, just a hostname and port. The page to navigate to needs to be present as well. For example, if the `filename` option was `home.html`, the following would work:

``` js
url: 'http://localhost:' + options.local.port + '/' + options.filename,
```

Since the `filename` option is not used for this purpose, there would need to be another property added to hold this value.

My suggestion would be to use Grunt's [files](http://gruntjs.com/configuring-tasks#files) option to allow users to specify groups of files.

**Comment by siygle** [comment]
Thanks for your advice, just follow grunt files format at v0.1.0.
