### ISSUE TITLE
Can I set asyn delay for autoshot?

### ISSUE THREAD

**Issue by qcgm1978** [siygle/grunt-autoshot#3]
Hellow everybody:
    The task can only display my partial page which loads some contents by AJAX. Can I set a delay and after that the task would autoshot? Can the developers implement the functionality  If no such option?

A little suggestion: the explanation of Readme file a little simple

```
please make sure phantomjs are in your PATH
```

I'm a noob so spent some time to know the meaning. For windows:

Download the phantomjs zip file and decompress it. 
Set the environment variable as phantomjs.exe's path. 
Restart powershell.

And I completed the path config.

Best Regards.

**Comment by siygle** [comment]
I will think about how to do with AJAX issue, maybe at next release, and thanks for your advice, actually I'm not familiar with windows system so thanks for your opinion,  I just add some comment for windows users.

**Comment by qcgm1978** [comment]
Thank you very much. I saw your answer just now.

**Comment by fini** [comment]
I just started using this awesome plugin, and while it's really great, the site i'm currently working on starts with a CSS Transition, unfortunately this makes all the screenshots basically black (bgcolor). It would be great with one or more features to address this, such as a simple options.delay to postpone when the screenshot is taken, or possibly some kind of callback or test function such as the options.preCreate pull request that was submitted by @wamberg.

**Comment by siygle** [comment]
Landed on e001cb7ace458a7db2cd53ce46aa3d47f15fcaa6.

Please upgrade to v0.2.0 
and use `delay` to assign how long to wait before take the screenshot.

**Comment by fini** [comment]
Awesome @Ferrari - It works like a charm, thanks a lot!

**Comment by siygle** [comment]
Thanks!
