### ISSUE TITLE
Cannot call method createPage of undefined

### ISSUE THREAD

**Issue by jaireina** [siygle/grunt-autoshot#7]
I'm getting this error when I try to run the grunt task:
Error: 'Fatal error: Cannot call method 'createPage' of undefined'

It's the same error reported here: 
http://stackoverflow.com/questions/19298207/grunt-autoshot-cannot-call-method-createpage-of-undefined/19750159#19750159

I uninstalled my phantomjs@1.9.2 and installed 1.9.0 and it worked! 

What changed from one version to another?

**Comment by adamcbrewer** [comment]
Yup same issue here. Thanks @jaireina for suggesting the 1.9.0 version!

**Comment by adamcbrewer** [comment]
I'm new to phantomJS myself, but I'm trying to ask them what would be throwing the [error on this line](https://github.com/Ferrari/grunt-autoshot/blob/master/tasks/autoshot.js#L49).

**Comment by mdarif** [comment]
I am also getting the same issue while running from yeoman generator-mobile.

Hope to hear from the dev soon.

**Comment by mdarif** [comment]
The same issue has been tracked here as well - https://github.com/yeoman/generator-mobile/issues/20

**Comment by mdarif** [comment]
https://github.com/yeoman/generator-mobile/issues/20#issuecomment-35687275

It's resolved for me, kindly check out the above link.

**Comment by bergie** [comment]
I wonder why autoshot doesn't use a bundled local phantomjs like many other grunt plugins do. Example: https://github.com/jdcataldo/grunt-mocha-phantomjs

Also, error handling would be nice :-)

**Comment by orangenpresse** [comment]
I fixed the problem with phantomjs 1.9.7 by changing the dependency version of "node-phantom-simple "in the package.json to 1.2.0

You also need to run "npm install" in the module folder again.
